import { MyUserContextProvider } from '@/utils/useUser'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from './provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Provider>
      <MyUserContextProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </MyUserContextProvider>
    </Provider>
  )
}
